import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartProvider from "../context/CartContext";
import AuthProvider from "../context/AuthContext";
import OrderProvider from "../context/OrderContext";
import WishlistProvider from "../context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <AuthProvider>

          <CartProvider>

            <OrderProvider>

              <WishlistProvider>

                {children}

              </WishlistProvider>

            </OrderProvider>

          </CartProvider>

        </AuthProvider>

      </body>
    </html>
  );
}
